version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx_container
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - 27018:27017
    volumes:
      - ../docker-volumes/mongo:/data/db

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - ../docker-volumes/redis:/data
